### ISSUE TITLE
Unable to commit my message in my branch.

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW6#21]
I have written code to Shift the FFT data. I am unable to commit message.
Error showing: **A file with the same name already exists. Please choose a different name and try again.**
I tried to change name as well, but still getting same response.

**Comment by kylemasc917** [comment]
Thats because laserlab already made a preparation.py file did you create a new one or edit the preexisting one?

**Comment by Priyanka-43** [comment]
Yeah, I changed now.
