### ISSUE TITLE
An issue with the .divcontainer

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW6#25]
I believe there's an issue with the .divcontainer, I'm not able to spot it though.
My code space was not functioning properly. I had to install python, create a virtual environment, and select an interpreter, and even then I was not able to use the terminal properly, it almost didn't recognize any command like pip and (git checkout).
I'm not sure what caused this problem.

**Comment by kylemasc917** [comment]
I had that issue last homework you have to make sure you create the codespace with the "default project configuration" and not the "python" option.

**Comment by HeshamElsaman** [comment]
Thanks, a lot! It worked!
