### ISSUE TITLE
blender (2 members!)

### ISSUE THREAD

**Issue by laserlab** [ubsuny/CP1-24-HW6#3]
Use blender to genrate a picture of a scene with a periodic structure bein 1m x 1m large and store it in a pandas dataframe that is exported to a pickle in the repository (2 members due Thursday midnight)

**Comment by ojha-aditya** [comment]
@avgagliardo do you think we should also include the code for generating the dataframe and pickle file with our PRs, that way we can better sync the format of the data files?

**Comment by avgagliardo** [comment]
Sure, I don't see any harm in that. Do you know what kind of structure you want to make?  I'll make sure to create something different.

**Comment by ojha-aditya** [comment]
Actually I am new to blender so maybe you can suggest the first idea? Something along Moire patterns was what I had in mind, but I do not know exactly how to implement that.

**Comment by avgagliardo** [comment]
Anything gridlike or node-based should be pretty straight-forrward to build.

It also depends if you want to build the scene manually or with scripts. You can do some pretty cool stuff with blender's object modifiers which require no scripting at all.

Here's a good place to start: https://docs.blender.org/manual/en/latest/modeling/modifiers/generate/array.html

https://m.youtube.com/watch?v=4zytiZczsps

You can combine two (or more) array modifiers to create some pretty interesting stuff.

**Comment by ojha-aditya** [comment]
Did you check the license part of the blender image?

**Comment by ojha-aditya** [comment]
@avgagliardo what is the format we are following? Should we do similar to PR #26?

**Comment by avgagliardo** [comment]
> @avgagliardo what is the format we are following? Should we do similar to PR #26?

yes, minimally we want to ship the rendered image as a pickle so that the other teams can work with the object but you may want to include a copy of the rendered image (and its 1m reference) for convenience.

**Comment by ojha-aditya** [comment]
Yeah I got that, what I meant was, would it be a good idea to push your code as well if it is different than the one in #26 so that the issue that arose in last homework with different data files having different formatting could be avoided?

> > @avgagliardo what is the format we are following? Should we do similar to PR #26?
> 
> yes, minimally we want to ship the rendered image as a pickle so that the other teams can work with the object but you may want to include a copy of the rendered image (and its 1m reference) for convenience.

**Comment by ojha-aditya** [comment]
Also, are we supposed to generate an image in which the periodic structure is 1m $\times$ 1m large or the entire image is scaled to that dimensions?

**Comment by ojha-aditya** [comment]
I have also submitted the data files in PR #32, I included two files as I was a bit confused as to whether our structure should be 3d or 2d. I also used another rendering software too along with blender. Working with blender was a little difficult because.

Oh and @avgagliardo good idea with the imagebb links, I also adopted that from your PR.

**Comment by avgagliardo** [comment]
> Yeah I got that, what I meant was, would it be a good idea to push your code as well if it is different than the one in #26 so that the issue that arose in last homework with different data files having different formatting could be avoided?
> 
> > > @avgagliardo what is the format we are following? Should we do similar to PR #26?
> > 
> > 
> > yes, minimally we want to ship the rendered image as a pickle so that the other teams can work with the object but you may want to include a copy of the rendered image (and its 1m reference) for convenience.

Sorry didn't see this until just now. 

The short answer is I reused the img_2_pickle script that @iglesias-cardinale used in his PR.  

The slightly longer version is that I started modifying the routine and giving it a few extra enhancements to make it general enough for all of our image conversions, but for the sake of not introducing new volatility in a file that has already been merged I just reused the same encoding and tested it locally to make sure there were no unexpected issues.

**Comment by avgagliardo** [comment]
> Also, are we supposed to generate an image in which the periodic structure is 1m × 1m large or the entire image is scaled to that dimensions?

I rendered an image in which the periodic structure itself has the dimensions of 1x1m, thats why I ended up removing the reference cube. I was getting cleaner FFT results without it, though I could bring it back if it was supposed to serve some other purpose.

**Comment by avgagliardo** [comment]
Closing issue now that both tasks are complete. Feel free to reopen if we need to make additional changes.
