### ISSUE TITLE
Rebuild container

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW6#31]
Did anyone receive a message while configuring codespace that the codespaces is running in recovery mode and a prompt to rebuild the container?

**Comment by ojha-aditya** [comment]
@kylemasc917 what should we go for a rebuild or full rebuild in this case?

**Comment by ojha-aditya** [comment]
Got it! I believe you have answered in #25. But why exactly does this arise?

**Comment by kylemasc917** [comment]
the default configuration runs the codespace using the devcontainer while the python option does not so it wont auto install the modules.

**Comment by ojha-aditya** [comment]
Understood! Thanks for answering.
